Repository ibm-build-lab/VAD-VAR-Workshop, pull requests merged in 2023-04, with the labels that each got.

#54 Various small fixes
  .github/pull_request_template.md
  content/Instana/104.md
  content/Instana/README.md
  content/Maximo/MAS-PREREQ.md
  content/Watson/101.md
  content/Watson/102.md
  content/Watson/105.md
  content/Watson/README.md
  gatsby-config.mjs
  package-lock.json
  package.json
  src/components/replacements/SmartLink.tsx
  src/pages/{mdx.fields__slug}.tsx
  src/plugins/remark-insert-jsx.mjs
  src/plugins/remark-relative-replace.mjs
  src/styles/globals.scss
Labels: enhancement, bug fix 🐛

#55 Instana: polish lab 2 and 3
  content/Instana/101.md
  content/Instana/102.md
  content/Instana/103.md
  content/Instana/104.md
  content/Instana/images/101/image-007-query.jpg
  content/Instana/images/101/image-007-query.png
Labels: Instana

#58 Fix hydration error
  .github/workflows/build-site.yml
  .github/workflows/deploy-static-site.yml
  .github/workflows/pull-request-testing.yml
  README.md
  content/Watson/101.md
  src/components/replacements/SubHeader.tsx
Labels: enhancement, bug fix 🐛

#59 Maurely/polish lab 4
  content/Instana/104.md
Labels: Instana

#62 Add syntax highlighting, fix relative links
  README.md
  content/Instana/README.md
  content/Maximo/README.md
  content/README.md
  content/Sterling/README.md
  content/Sterling/docs/ClientDemonstration.md
  content/Sterling/docs/ConfigurationPart1.md
  content/Sterling/docs/ConfigurationPart2.md
  content/Sterling/docs/DemoPreparation-OCPlogon.md
  content/Sterling/docs/HTTPAdapter.md
  content/Sterling/docs/NextSteps.md
  content/Sterling/docs/Overview.md
  content/test.md
  gatsby-config.mjs
  package-lock.json
  package.json
  src/components/Layout.tsx
  src/components/SEO.tsx
  src/components/SideBar.tsx
  src/components/TableOfContents.tsx
  src/components/replacements/BlockQuote.tsx
  src/components/replacements/CodeBlock.tsx
  src/components/replacements/QuizAlert.tsx
  src/components/replacements/SmartLink.tsx
  src/components/replacements/index.ts
  src/globals.d.ts
  src/helpers/create-theme.mjs
  src/helpers/useSiteMetaData.ts
  src/hooks/useSiteMetaData.ts
  src/pages/{mdx.fields__slug}.tsx
  src/styles/components/replacements/BlockQuote.module.scss
  src/styles/components/replacements/CodeBlock.module.scss
  src/styles/pages/{mdx.fields__slug}.module.scss
  static/theme-template.json
Labels: enhancement

#68 Add quiz alerts to the WA content
  content/Watson/102.md
  content/Watson/103.md
Labels: documentation
