Repository ibm-build-lab/VAD-VAR-Workshop, pull requests merged in 2024-03, with the labels that each got.

#349 Content changes: LLM-powered search has been updated to use IBM Granite
  content/Watsonx/Assistant/Level-4/203.es.md
  content/Watsonx/Assistant/Level-4/203.md
Labels: watsonx Assistant

#360 fix: Ensure dates conform to ISO format
  content/Watsonx/Orchestrate/103.es.md
  content/Watsonx/WatsonxAI/101.es.md
  content/Watsonx/WatsonxAI/104.es.md
  content/Watsonx/WatsonxAI/105.es.md
  content/Watsonx/WatsonxAI/106.es.md
  content/Watsonx/WatsonxAI/107.es.md
  content/Watsonx/WatsonxAI/108.es.md
  content/Watsonx/WatsonxAI/109.md
  content/Watsonx/WatsonxAI/Level-4/203.es.md
  content/Watsonx/WatsonxAI/Level-4/204.es.md
  content/Watsonx/WatsonxData/102.es.md
  content/Watsonx/WatsonxData/103.es.md
  content/Watsonx/WatsonxData/104.es.md
  content/Watsonx/WatsonxData/105.es.md
  content/Watsonx/WatsonxData/106.es.md
  content/Watsonx/WatsonxData/107.es.md
  content/Watsonx/WatsonxData/108.es.md
  content/Watsonx/WatsonxData/109.es.md
  content/Watsonx/WatsonxData/110.es.md
  content/Watsonx/WatsonxData/Level-4/201.es.md
  content/Watsonx/WatsonxData/Level-4/202.es.md
  content/Watsonx/WatsonxData/Level-4/203.es.md
  content/Watsonx/WatsonxData/Level-4/204.es.md
  content/Watsonx/WatsonxData/ref100.es.md
  content/Watsonx/WatsonxData/ref101.es.md
  content/Watsonx/WatsonxData/ref102.es.md
  content/Watsonx/WatsonxGov/1.es.md
  content/Watsonx/WatsonxGov/1.md
  content/Watsonx/WatsonxGov/102.es.md
  content/Watsonx/WatsonxGov/102.md
  content/Watsonx/WatsonxGov/103.es.md
  content/Watsonx/WatsonxGov/103.md
  content/Watsonx/WatsonxGov/104.es.md
  content/Watsonx/WatsonxGov/104.md
  content/Watsonx/WatsonxGov/105.es.md
  content/Watsonx/WatsonxGov/105.md
  content/Watsonx/WatsonxGov/106.es.md
  content/Watsonx/WatsonxGov/106.md
Labels: bug fix 🐛

#365 WCA for Z Spanish Translations
  content/Watsonx/CodeAssistant/Ansible-Lightspeed/101.es.md
  content/Watsonx/CodeAssistant/Ansible-Lightspeed/102.es.md
  content/Watsonx/CodeAssistant/Ansible-Lightspeed/103.es.md
  content/Watsonx/CodeAssistant/Ansible-Lightspeed/104.es.md
  content/Watsonx/CodeAssistant/Ansible-Lightspeed/README.es.md
  content/Watsonx/CodeAssistant/README.es.md
  content/Watsonx/CodeAssistant/Z/111.es.md
  content/Watsonx/CodeAssistant/Z/112.es.md
  content/Watsonx/CodeAssistant/Z/113.es.md
  content/Watsonx/CodeAssistant/Z/114.es.md
  content/Watsonx/CodeAssistant/Z/README.es.md
Labels: Translation
